project:
  type: website
  output-dir: docs

website:
  title: "Forest Research Decision Support System API Documentation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - UsingESCWCC-Pyton.qmd
format:
  html:
    theme: default
    mainfont: serif
    fontsize: 1.5rem
    fontcolor: "#0013d5"
    linkcolor: "#ff33f0"
    monofont: courier new
    backgroundcolor: "#ffffff"
    css: styles.css
    toc: true