project:
  type: website
  output-dir: docs

website:
  title: "FR DSS API Documentation"
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "ESC"
        contents:
          - UsingESCWCCAPI.qmd

format:
  html:
    theme: light
    code-copy: true
    fontsize: 1rem
    fontcolor: "#000000"
    linkcolor: "#2943d6"
    monofont: courier new
    backgroundcolor: "#ffffff"
    css: styles.css
    toc: true
    toc-title: Contents
    toc-location: left
    smooth-scroll: true
    grid:
      sidebar-width: 250px
      body-width: 1000px
      margin-width: 300px