project:
  type: website
  output-dir: docs

website:
  title: "Forest Research Decision Support System API Documentation"
  navbar:
    left:
      - UsingESCWCC-Pyton.qmd
format:
  html:
    theme: minimal
    mainfont: arial
    fontsize: 1.5rem
    fontcolor: "#0013d5"
    linkcolor: "#ff33f0"
    monofont: courier new
    backgroundcolor: "#a5aaac"
    css: styles.css
    toc: true